version: '3.9'

services:
  web:
    build:
      context: ./web
      dockerfile: Dockerfile
    ports:
      - 3000:3000
    volumes:
      - ./web:/app
    tty: true
  
  restapi:
    build:
      context: ./restapi
      dockerfile: Dockerfile
    ports:
      - 8000:8000
    tty: true
    command: python manage.py runserver 0.0.0.0:8000

