version: '3.9'

services:
  nginx:
    image: nginx:mainline-alpine
    depends_on:
      - restapi
      - web
    ports:
      - 8080:8081
    volumes:
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
    networks:
      backend:
        aliases:
          - local.django.api

  web:
    build:
      context: ./web
      dockerfile: Dockerfile
    ports:
      - 3000:3000
    volumes:
      - ./web:/app
    tty: true
  
  api:
    build:
      context: ./restapi
      dockerfile: Dockerfile
    ports:
      - 8000:8000
    tty: true
    networks:
      backend:
        aliases:
          - local.django.apiroute
    command: python manage.py runserver 0.0.0.0:8000

networks:
  backend:

